source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem "cmor", path: "../"
gem "cmor-core-api", path: "../cmor-core-api"
gem "cmor-contact", path: "../cmor-contact"
gem "rao-active_collection", path: "~/projects/gems/rao/rao-active_collection"
gem "rao-api-resources_controller", path: "~/projects/gems/rao/rao-api-resources_controller"
gem 'rails', '~> 7.0'
