# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem "cmor", path: "../"
gem "cmor-core-settings", path: "../cmor-core-settings"
gem "rails", "~> 7.0"
