source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem "cmor", path: "../"
gem "cmor-core-api", path: "../cmor-core-api"
gem "cmor-galleries", path: "../cmor-galleries"
gem "rails", "~> 7.0"
